config/routes.rb
CardapioNaMao::Application.routes.draw do
  resources :itens

	resources :categorias
		
	devise_for :users
	
	match 'categorias_json' => 'categorias#all_categorias_from_user'
	match 'itens_json' => 'itens#all_itens_from_user'	
	match 'download' => redirect('/CardapioNaMao.apk')	
	match 'home' => 'pagina_inicial#index'
	match 'ajuda' => 'pagina_inicial#ajuda'

	root :to => "pagina_inicial#index"	
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
	belongs_to :user
	has_many :itens, :dependent => :destroy
	validates :nome, :length => { :maximum => 30 }
	validates_presence_of :nome	
	
	validates_presence_of :user
	validates_associated :user

	validates_uniqueness_of :nome, :case_sensitive => false, :scope => [:user_id]
		
end

app/models/item.rb
class Item < ActiveRecord::Base	
		
	belongs_to :categoria
	validates :nome, :length => { :maximum => 50 }
	validates_uniqueness_of :nome, :case_sensitive => false, :scope => [:categoria_id]
	validates_presence_of :nome, :message => 'deve ser preenchido.'
	validates_numericality_of :preco, :greater_than => 0, :message => 'deve ser maior que zero.'
	
	validates_presence_of :categoria
	validates_associated :categoria
	
	has_attached_file :imagem, 
		:storage => :s3,
		:s3_credentials => Rails.root.join('config/s3.yml'),
		:path => "/:style/:id",
		:styles => { :medium => "300x300>", :thumb => "100x100#", :original => "800x600>" }
				
	validates_attachment_size :imagem, :less_than => 500.kilobytes		
	
	def url_imagem
		if imagem_file_name		
			imagem.to_s
		else
			''
		end
	end	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :categorias, :dependent => :destroy

  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include CategoriasHelper
  include ItensHelper
  include DateHelper
  include JsonHelper
end

app/controllers/categorias_controller.rb
# coding: utf-8
class CategoriasController < ApplicationController
  before_filter :authenticate_user!, :except => [:all_categorias_from_user]
  before_filter :remove_json_root!, :only => [:index, :all_categorias_from_user, :show]

  respond_to :html, :xml, :json
  
  def index
    @categorias = get_all_categorias_from_user(current_user).paginate :page => params['page'], :per_page => 10

    respond_with @categorias
  end

  def all_categorias_from_user
    user = User.find_by_email params[:email]

    data = convert_date_to_appropriate_format params[:data]

    if user
      @categorias = get_categorias_from_user_by_date user, data
      respond_with @categorias
    else
      respond_with '{"erro":"Usuário Inválido."}'
    end
  end

  def new
    @categoria = Categoria.new

    respond_to do |format|
      format.html
    end
  end

  def edit
    @categoria = Categoria.find(params[:id])
  end

  def create
    @categoria = Categoria.new(params[:categoria])
    @categoria.user = current_user

    respond_to do |format|
      if @categoria.save
        format.html { redirect_to(categorias_url, :notice => 'Categoria cadastrada com sucesso.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @categoria = Categoria.find(params[:id])

    respond_to do |format|
      if @categoria.update_attributes(params[:categoria])
        format.html { redirect_to(categorias_url, :notice => 'Categoria alterada com sucesso.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @categoria = Categoria.find(params[:id])

    respond_to do |format|
      if @categoria.itens.empty?
        @categoria.destroy
        format.html { redirect_to(categorias_url, :notice => 'Categoria excluída com sucesso.') }
      else
        format.html { redirect_to(categorias_url, :alert => 'Não foi possível excluir a categoria "' + @categoria.nome + '", ela possui itens associados.') }
      end
    end
  end
end

app/controllers/itens_controller.rb
# coding: utf-8
class ItensController < ApplicationController
  before_filter :remover_currency, :only => [:create, :update]
  before_filter :authenticate_user!, :except => [:all_itens_from_user]
  before_filter :remove_json_root!, :only => [:index, :all_itens_from_user, :show]
  
  respond_to :html, :xml, :json
  
  def index
    @itens = get_all_itens_from_user(current_user).paginate :page => params['page'], :per_page => 10
    respond_with @itens
  end

  def all_itens_from_user
    user = User.find_by_email params[:email]

    data = convert_date_to_appropriate_format params[:data]

    if user
      @itens = get_itens_from_user_by_date user, data
      respond_with @itens
    else
      respond_with '{"erro":"Usuário Inválido."}'
    end
  end

  def new
    @item = Item.new
    @operation = 'create'
    @categorias = get_all_categorias_from_user(current_user)
    respond_to do |format|
      format.html
    end
  end

  def edit
    @item = Item.find(params[:id])
    @operation = 'update'
    @categorias = get_all_categorias_from_user(current_user)
  end

  def create
    @item = Item.new(params[:item])
    respond_to do |format|
      if @item.save
        format.html { redirect_to(itens_url, :notice => 'Item cadastrado com sucesso.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @item = Item.find(params[:id])
        
    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to(itens_url, :notice => 'Item atualizado com sucesso.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to(itens_url, :notice => 'Item excluído com sucesso.') }
      format.xml  { head :ok }
    end
  end

  protected
  def remover_currency
    params[:item][:preco] = params[:item][:preco].to_s.gsub(/[^0-9,]/,'').gsub(/,/,'.').to_f
  end
end

app/controllers/pagina_inicial_controller.rb
class PaginaInicialController < ApplicationController
  before_filter :authenticate_user!
  def index
  end

  def ajuda
  end

  def download
    send_data('public/CardapioNaMao.apk')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
  def get_all_categorias_from_user(user)
    get_categorias_from_user_by_date user, Time.at(0)
  end

  def get_categorias_from_user_by_date(user, date)

    return Array.new if not user

    categorias = Categoria.order('nome ASC').where('updated_at > ?', date).find_all_by_user_id user.id

    return Array.new if not categorias

    categorias
  end

end

app/helpers/date_helper.rb
module DateHelper
	def convert_date_to_appropriate_format(data)
	
		if data
			data = Time.at data.to_i
		else
			data = Time.at 0
		end
		
		data
	end			
end

app/helpers/itens_helper.rb
module ItensHelper
	def get_all_itens_from_user(user)	
		get_itens_from_user_by_date user, Time.at(0)
	end
	
	def get_itens_from_user_by_date(user, date)
	
		itens = Array.new
		
		return itens if user == nil
	
		if user.categorias		
			user.categorias.each do |categoria|					
				if categoria.itens		
					categoria.itens.each do |item|
						if item.updated_at > date
							itens << item
						end
					end				
				end
			end		
		end
		
		itens.sort! { |a, b| a.nome.downcase <=> b.nome.downcase }		
	end
	
	def self.tamanho_maximo_upload
		500.kilobytes
	end
end

app/helpers/json_helper.rb
module JsonHelper
  def remove_json_root!
    ActiveRecord::Base.include_root_in_json = false
  end
end

app/helpers/moeda_helper.rb
module MoedaHelper
	def moeda(campo)
		number_to_currency campo, :precision => 2, :unit => "R$ ", :separator => ",", :delimiter => ""
	end				
end

app/helpers/pagina_inicial_helper.rb
module PaginaInicialHelper
	def links_superiores
		
	end
end

app/helpers/registration_helper.rb
module RegistrationHelper
	def show_devise_error_messages!
		return "" if resource.errors.empty?

		messages = resource.errors.full_messages.map { |msg| content_tag(:div, msg, :class => "error") }.join		

		html = <<-HTML
			<div class="div_error">
				#{messages}
			</div>
		HTML

		html.html_safe
	end
		
end

app/views/categorias/_form.html.erb
<%= content_for :js do%>
	<script type="text/javascript">
		$(document).ready(function(){
			$('#categoria_nome').select();	

			$('form').keyup(function(e){
				if(e.keyCode == 13 && !$.browser.webkit)
				{
					$('#btnSubmit').click();
				}
			});
		});
	</script>
	<!--[if IE]>
	<script>
		$(document).ready(function(){
			$("#categoria_nome").focus();
		});
	</script>
	<![endif]-->
<% end %>

<%= form_for(@categoria) do |f| %>
  <% if @categoria.errors.any? %>
  
    <div class="error_explanation">
      <h2>Erro ao cadastrar categoria:</h2>

      <ul>
		<% @categoria.errors.full_messages.each do |msg| %>
			<li class="error"><%= msg %></li>
		<% end %>
      </ul>
    </div>
	
  <% end %>

  <div class="field">
	<div>
		<%= f.label :nome %>
	</div>
    <div>
		<%= f.text_field :nome, :class => 'input' %>
	</div>
  </div>
  <br/>
  <div class="actions">    
	<%= link_to "Voltar", {:action => 'index'}, {:class => 'button white'} %>
	<%= link_to_function "Salvar", "$('form').submit()" ,{:class => 'button white', :id => 'btnSubmit'} %>	
  </div>
<% end %>

app/views/categorias/edit.html.erb
<h1>Categoria</h1>

<%= render 'form' %>

app/views/categorias/index.html.erb
<h1>Categorias</h1>

<div class="wrapper_tabela">
	<%= content_tag(:p, flash[:alert], :class => "error") if flash[:alert] %>
	<%= content_tag(:p, flash[:notice], :class => "success") if flash[:notice] %>

	<% if @categorias.empty? %>
		<p>Nenhuma categoria cadastrada.</p>
	<% else %>
		<table class="tabela">
			<thead>
				<tr>
					<th>Nome</th>
					<th class="icones_tabela"></th>			
					<th class="icones_tabela"></th>
				</tr>
			</thead>
			<tbody>
				<% @categorias.each do |categoria| %>
					<tr>
						<td><%= categoria.nome %></td>				
						<td><%= link_to image_tag('/images/botao/editar.png', :border => 0), edit_categoria_path(categoria) %></td>
						<td><%= link_to image_tag('/images/botao/trash.gif', :border => 0), categoria, :confirm => 'Deseja remover esta categoria?', :method => :delete %></td>
					</tr>
				<% end %>
			<tbody>
		</table>
	<% end %>

	<br />

	<%= will_paginate @categorias, :next_label => "Próximo >>", :previous_label => "<< Anterior"%>
</div>
<%= link_to "Nova", {:action => 'new'}, {:class => 'button white'} %>

app/views/categorias/new.html.erb
<h1>Categoria</h1>

<%= render 'form' %>

app/views/itens/_form.html.erb
<%= content_for :js do%>
	<script type="text/javascript">
		$(document).ready(function(){
			$('#campo_arquivo').hide();
			$('#item_nome').select();
			$('#item_preco').priceFormat({
				prefix: 'R$ ',
				centsSeparator: ',',
				thousandsSeparator: '',
				centsLimit: 2
			});
			
			$('form').keyup(function(e){
				if(e.keyCode == 13 && !$.browser.webkit)
				{
					$('#btnSubmit').click();
				}
			});
			
			$('#new_item').submit(function(){
				var arquivo = $('#item_imagem').get(0);
				if(arquivo.files != null && arquivo.files.length > 0)
				{
					if(arquivo.files[0].size > <%= ItensHelper.tamanho_maximo_upload %>)
					{
						alert('Tamanho máximo para as imagens é 500kb.');
						return false;
					}
					else
					{
						var isJPG = arquivo.files[0].name.match('jpg$');
						var isBMP = arquivo.files[0].name.match('bmp$');
						var isGIF = arquivo.files[0].name.match('gif$');
						var isPNG = arquivo.files[0].name.match('png$');
						if(isJPG || isBMP || isGIF || isPNG)
						{
							return true;						
						}
						else
						{
							alert('Extensão inválida para o arquivo.');
							return false;
						}
					}
				}
			});
		});
	</script>
	<!--[if IE]>
	<script>
		$(document).ready(function(){
			$("#item_nome").focus();
		});
	</script>
	<![endif]-->
<% end %>

<%= form_for(@item, :html => { :multipart => true }, :url => {:action => @operation}) do |f| %>

  <% if @item.errors.any? %>
    <div class="error_explanation">
      <h2>Erro ao cadastrar item:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	<div>
		<%= f.label :nome %>
	</div>
    <div>
		<%= f.text_field :nome, :class => 'input' %>
	</div>    
  </div>
  <div class="field">
	<div>
		<%= f.label :categoria_id %>
	</div>
    <div>
		<%= f.collection_select(:categoria_id,
			@categorias,
			:id, :nome, {:prompt => "Selecione"}, {:class => 'input'}) %>		
	</div>     
  </div>
  <div class="field">
	<div>
		<%= f.label :descricao, "Descrição"%>
	</div>
    <div>
		<%= f.text_field :descricao, :class => 'input' %>		
	</div>    
  </div>
  <div class="field">
	<div>
		<%= f.label :preco, "Preço"%>
	</div>
    <div>		
		<%= f.text_field :preco, :class => 'input' %>				
	</div> 	
  </div>
  <div class="field">
	<div>
		<%= f.label :imagem %>
	</div>
	<% if @item.url_imagem.empty? %>
		<div>
			<%= f.file_field :imagem, :class => 'input' %>		
		</div>
	<% else %>
		<div id="div_imagem">
			<%= image_tag @item.imagem.url(:thumb) %>
			<%= link_to_function "Trocar Imagem", "$('#campo_arquivo').show();$('#div_imagem').hide();"%>
		</div>
		<div id="campo_arquivo">
			<%= f.file_field :imagem, :class => 'input' %>		
			<%= link_to_function "Cancelar", "$('#campo_arquivo').hide();$('#div_imagem').show();"%>
		</div>
	<% end %>	
  </div>
  <br/>
  <div class="actions">    		
	<%= link_to "Voltar", {:action => 'index'}, {:class => 'button white'} %>
	<%= link_to_function "Salvar", "$('form').submit()" ,{:class => 'button white', :id => 'btnSubmit'} %>	
  </div>
<% end %>

app/views/itens/edit.html.erb
<h1>Item</h1>

<%= render 'form' %>

app/views/itens/index.html.erb
<h1>Itens</h1>

<div class="wrapper_tabela">
	<%= content_tag(:p, flash[:alert], :class => "error") if flash[:alert] %>
	<%= content_tag(:p, flash[:notice], :class => "success") if flash[:notice] %>
	<% if @itens.empty? %>
		<p>Nenhum item cadastrado.</p>
	<% else %>
		<table class="tabela">
			<thead>
				<tr>
					<th>Nome</th>
					<th>Categoria</th>    
					<th>Descrição</th>
					<th>Preço</th>    
					<th class="icones_tabela"></th>
					<th class="icones_tabela"></th>
				</tr>
			</thead>
			<tbody>
				<% @itens.each do |item| %>
					<tr>
						<td><%= item.nome %></td>
						<td><%= item.categoria.nome %></td>    
						<td><%= item.descricao %></td>
						<td><%= moeda item.preco%></td>    
						<td><%= link_to image_tag('/images/botao/editar.png', :border => 0), edit_item_path(item) %></td>
						<td><%= link_to image_tag('/images/botao/trash.gif', :border => 0), item, :confirm => 'Deseja remover este item?', :method => :delete %></td>				
					</tr>
				<% end %>
			</tbody>
		</table>
	<% end %>
	<br />

	<%= will_paginate @itens, :next_label => "Próximo >>", :previous_label => "<< Anterior"%>
</div>
<%= link_to "Novo", {:action => 'new'}, {:class => 'button white'} %>

app/views/itens/new.html.erb
<h1>Item</h1>

<%= render 'form' %>

app/views/itens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @item.nome %>
</p>

<p>
  <b>Categoria:</b>
  <%= @item.categoria_id %>
</p>

<p>
  <b>Imagem:</b>
  <%= image_tag @item.imagem.url(:thumb) %>
</p>


<%= link_to 'Editar', edit_item_path(@item) %> |
<%= link_to 'Voltar', itens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cardápio na Mão</title>
  <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" /> 
  <% if content_for? :css %>
		<%= yield :css %>		
	<% else %>			
		<%= stylesheet_link_tag "main" %>		
	<% end %>
	<%= stylesheet_link_tag "botao" %>
  <%= csrf_meta_tag %>  	
</head>
<body id="admin" class="clientdashboard">	
	<% if content_for? :login %>
		<%= yield :login %>
	<% else %>
		<div class="adminNavsWrapper">
			<div class="adminNavs">
				<ul>					
					<li id="adminNavsOn2">
						<%= link_to home_path do%>
							<span>Home</span>
						<% end %>						
					</li>
					<li>
						<%= link_to categorias_path do%>
							<span>Categorias</span>
						<% end %>
					</li>
					<li>
						<%= link_to itens_path do%>
							<span>Itens</span>
						<% end %>						
					</li>
					<li>
						<%= link_to download_path do%>
							<span>Download</span>
						<% end %>						
					</li>					
				</ul>
			</div>
			<div class="adminNavs adminRight">
				<ul>		
					<li>
						<%= link_to ajuda_path do%>
							<span>Ajuda</span>
						<% end %>						
					</li>
					<li>
						<%= link_to destroy_user_session_path do%>
							<span>Logout</span>
						<% end %>						
					</li>					
				</ul>
			</div>
			<div class="clear"></div>
		</div>
		<div class="clear"></div>
		<div class="case">
			<div class="shadowHeader">
				<div class="shadowMidLeft">
					<div id="header">
						<h1><a href="#">Cardápio na Mão</a></h1>
					</div>
				</div>
			</div>
			<div class="shadowWrap">
				<div class="shadowMidLeft">
					<div class="shadowMidContent">
						<div id="dashboard">
							<%= yield %>
						</div>
					</div>
				</div>
			</div>
			<div class="shadowBottomLeft">
				<div class="shadowMidLeft">
				</div>
			</div>			
		</div>
		
	<% end %>	
	<%= javascript_include_tag :defaults %>
	<%= javascript_include_tag 'jquery.price_format.1.3' %>
	<!--[if lte IE 6]>
		<%= javascript_include_tag 'supersleight-min.js' %>		
	<![endif]--> 
	<% if content_for? :js %>
		<%= yield :js %>						
	<% end %>
</body>
</html>

app/views/pagina_inicial/ajuda.html.erb
<p>Utilize os menus superiores para realizar as operações<p>

app/views/pagina_inicial/index.html.erb
<p>Seja bem vindo ao Cardápio Na Mão<p>